name: Deploy to Render

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'render.yaml'
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Render CLI
        run: |
          npm i -g render-cli@1

      - name: Render Blueprint Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render blueprint deploy --auto-approve --yes --from-file render.yaml

      - name: Show services
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render services list | sed -n '1,120p'
